### ISSUE TITLE
optimality of galeShapleyMatching

### ISSUE THREAD

**Issue by HakanHolmberg** [jtilly/matchingR#21]
Hi I am very new to SM problems but I have a hard time understanding how the input to the galeShapleyMatching() algorithm should look like. Until now I have interpreted a preference ordering as a vector with reviewer id's in descending order of preference, first position in vector means most preferred reviewer etc.
  I have interpreted utility cardinals as if position i in the utility cardinal vector has the highest number then proposer i is the most preferred, I did see that the definition of utility cardinals also stated a bijective relationsship with {1,..,n}.
  When using this interpretation I get some odd results,
proposerPref <- matrix(c(2,1,1,2),nrow=2) 
reviewerUtils <- matrix(c(1,2,2,1),nrow=2)     
galeShapleyMatching(proposerPref, reviewerUtils) 
OUTPUT
$proposals
     [,1]
[1,]    1
[2,]    2
$engagements
     [,1]
[1,]    2
[2,]    0

I expected a 1 instead of a 0, could you please explain this to me if you have time

Best regards
Haakan

**Comment by njanetos** [comment]
Take a look at using `one2one` instead, the function you called is not meant to be used by the user. `galeShapleyMatching` is the R wrapper for the C++ function which runs the Gale-Shapley algorithm. In particular it expects zero indices, very special formatting, and doesn't complain if it gets strange input. 

Really, the documentation should be more explicit in suggesting that users use `one2one`.

**Comment by HakanHolmberg** [comment]
thanks, one2one() works as expected, I was going through the documentation trying out all functions documented,  but I will read the introductory vignette.
