### ISSUE TITLE
Is it possible to determine slots (in College Admissions Problem) as a vector?  

### ISSUE THREAD

**Issue by p2004r** [jtilly/matchingR#30]
Currently, "slots" is the number of slots that each college has available. But is possible each college may a different number of slots.

Is it possible to change this input parameter of the algorithm?

**Comment by jtilly** [comment]
That's not possible in the current version of the package. However, it's an easy fix. We would need to change what's happening in lines 293-294 and 339-340 in [R/galeShapley.R](https://github.com/jtilly/matchingR/blob/master/R/galeshapley.R#L293). There, we're expanding the preference matrices of students and colleges to account for the number of slots. I'll take a look at it. Seems like something we can easily implement.

**Comment by p2004r** [comment]
Thank you very much for your attention!

I think to corresponding change a "matrix" to a "list" in this place? https://github.com/jtilly/matchingR/blob/master/R/galeshapley.R#L315

PS Or (without changing the type), only replace the missing value in the res$matched.colleges (at the college with smaller "slots") on Na?

**Comment by jtilly** [comment]
Yes, we need to change the output type. I'm thinking a list is the way to go, because I'd like to reserve 'NA' for colleges with slots that remain unmatched.

**Comment by jtilly** [comment]
I think I have a basic version of this working. The code is on a separate [branch](https://github.com/jtilly/matchingR/tree/feature/slots). Still needs further testing.

**Comment by jtilly** [comment]
Done and merged into master.
