### ISSUE TITLE
Compute all stable matchings

### ISSUE THREAD

**Issue by jtilly** [jtilly/matchingR#32]
@thiloklein suggested that we add an algorithm that computes _all_ stable matchings for the marriage market. The Gale-Shapley algorithm only computes two of potentially many stable matchings (either the male-optimal or the female-optimal matching).

The algorithm to compute all stable matchings is described in Gusfield and Irving (1989) on p 121. There's a Java implementation [here](http://www.dcs.gla.ac.uk/~pat/jchoco/roommates/toolkit/matching_toolkit.zip). The algorithm is implemented in `SMAllMatchingsByRotationsImpl.java`.

**Comment by njanetos** [comment]
I read through the algorithm in Gusfield and Irving. The explanation and results in that chapter seem to be dependent on terminology introduced in chapter 2 of that book, which we don't have. Is whatever setup they introduce in chapter 2 standard in this literature? A quick google search is uninformative. If not, can @thiloklein share chapter 2 with us?

**Comment by jtilly** [comment]
Yeah, this isn't going to happen.
