### ISSUE TITLE
Use package microbenchmark conditionally

### ISSUE THREAD

**Issue by njanetos** [jtilly/matchingR#35]
As per Brian Ripley's direction:

> 'microbenchmark' is a package that does not work at all on some platforms (e.g. Sparc Solaris) and is flaky on others (e.g. my Windows laptop).  And its nominal maintainer has vanished.
>
> This makes it undesirable for packages to strictly depend on it, but packages
>
> `anMC timeit`
>
> do.  Also, if it is used in Suggests: it should be used conditionally (see §1.1.3.1 of the manual), but packages
>
> `JacobiEigen R6 aoos base64url brotli checkmate cubature fourierin funrar matchingR mkin rtrie rucrdtw schumaker storr tibble wrswoR`
>
> do not do so.

Please update your package(s).

**Comment by jtilly** [comment]
I'm sort of okay with not supporting Solaris and windows laptops.

**Comment by jtilly** [comment]
Include the package conditionally or don't use it unconditionally. I opted for the latter.

**Comment by njanetos** [comment]
It's this sort of lateral thinking that gets one an econometrica.
